name: Deploy Project
on: [push, workflow_dispatch] # Trigger case, run it on push. We can also add multiple events, that means i can trigger tis event also manually too.
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
      - name: Example step
        run: |
          echo "The value of ALLOWED_USER is ${{ vars.ALLOWED_USER }}"
     
      - name: Check User
        run: |
          echo $ALLOWED_USER
          echo $env.ALLOWED_USER
          IFS=',' read -ra ALLOWED_USER <<< "$ALLOWED_USER"
          for user in "${ALLOWED_USER[@]}"; do
            if [[ "$user" == "$GITHUB_ACTOR" ]]; then
              echo "User $GITHUB_ACTOR is allowed to trigger the pipeline"
              exit 0
            fi
          done
          echo "$user"
          echo "User $GITHUB_ACTOR is not allowed to trigger the pipeline"
          exit 1
          
      - name: Get code
        uses: actions/checkout@v3 # Hazir marketplace actionslarini bu sekilde kullaniyoruz. 'run' yerine 'uses'. with ile bir parametre eklemedim cunku default olarak attached oldugu repositoryde calisir
      - name: Install NodeJS # Zorunlu degil cunku github runnerlarinda otomatik olarak yuklu geliyor.
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependicies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
  deploy:
    needs: test # Deploy job needs test job to finish to start.
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files # name should be same in order download that artifact
      - name: Output content
        run: ls
      - name: Install NodeJS 
        uses: actions/setup-node@v3
        with:
          node-version: 18
        

#test


















        
